#!/bin/sh

if [ "$NO_TEMPLATE" = "true" ]; then
  exit 0
fi

if [ "$2" = '' ]; then
  mv $1 $1.tmp
  ISSUE_NUMBER=`git rev-parse --abbrev-ref @ | sed -e 's/^[^0-9]*\([0-9]*\).*/\1/'`
  if [ ! -z $ISSUE_NUMBER ]; then
    ORIGIN=`git remote get-url origin`
    BRANCH=`git branch --show-current`
    if [ ! -z $JIRA_PREFIX ]; then
      echo "${JIRA_PREFIX}-${ISSUE_NUMBER} \c" > $1
    else
      echo "[#${ISSUE_NUMBER}] \c" > $1
    fi
  fi
  cat $1.tmp >> $1
fi
