#!/bin/sh

if [ "$2" = '' ]; then
  mv $1 $1.tmp
  ISSUE_NUMBER=`git rev-parse --abbrev-ref @ | sed -e 's/^[^0-9]*\([0-9]*\).*/\1/'`
  if [ ! -z $ISSUE_NUMBER ]; then
    ORIGIN=`git remote get-url origin`
    if echo $ORIGIN | grep -q 'github'; then
      echo "[#${ISSUE_NUMBER}] \c" > $1
    elif echo $ORIGIN | grep -q 'spdly'; then
      echo "${JIRA_PREFIX}-${ISSUE_NUMBER} \c" > $1
    else
      echo "[#${ISSUE_NUMBER}] \c" > $1
    fi
  fi
  cat $1.tmp >> $1
fi
