#!/bin/sh

if [ -n ".rubcop.yml" ]; then
  git diff --cached --name-only --diff-filter=AM | grep '\.rb$' | xargs rubocop
  cop=$?
  if [ $cop -eq 1 ]; then
    cached=`git diff --cached --name-only --diff-filter=AM | grep '\.rb$'`
    echo $cached | xargs rubocop -a
    echo $cached | xargs git add
  fi
  exit $cop
fi
