[[plugins]]
repo  = 'vim-coffee-script'
on_ft = ['coffee']
[[plugins]]
repo = 'awetzel/elixir.nvim'
on_ft = ['elixir']
build = '''./install.sh'''
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['ansible']
[[plugins]]
repo = 'dag/vim-fish'
on_ft = ['fish']
[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = ['elixir']
[[plugins]]
repo  = 'elzr/vim-json'
on_ft = ['json']
[[plugins]]
repo  = 'fatih/vim-go'
on_ft = ['go']
[[plugins]]
repo = 'itmammoth/run-rspec.vim'
on_ft = ['ruby']
[[plugins]]
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript']
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
[[plugins]]
repo = 'lervag/vim-latex'
on_ft = ['tex']
[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascript.jsx']
[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascript.jsx']
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']
[[plugins]]
repo  = 'rhysd/vim-crystal'
on_ft = ['crystal']
[[plugins]]
repo = 'Shougo/denite.nvim'
on_event = 'BufRead'
hook_add = '''
nmap <silent> <C-u><C-f> :<C-u>Denite filetype<CR>
nmap <silent> <C-u><C-p> :<C-u>Denite file_rec<CR>
nmap <silent> <C-u><C-j> :<C-u>Denite line<CR>
nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>
nmap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR>
nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR>
nmap ml :<C-u>call denite#start([{'name': 'file_rec', 'args': [g:memolist_path]}])<CR>
'''
hook_post_source = '''
call denite#custom#var('grep', 'default_opts', [])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#source('file_rec', 'matcher', ['matcher_cpsm', 'matcher_fuzzy'])
'''
[[plugins]]
repo  = 'Shougo/deoplete.nvim'
on_i = 1
[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1
[[plugins]]
repo  = 'slim-template/vim-slim'
on_ft = ['slim']
[[plugins]]
repo  = 'tpope/vim-endwise'
on_ft = ['ruby']
[[plugins]]
repo  = 'tpope/vim-rails'
on_ft = ['ruby']
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']
